# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build Application
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
  branches:
    master:
    - step:
        name: Build Application
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
    - step:
        name: Tag Code
        caches:
          - node
        script:
          - git tag release-$BITBUCKET_BUILD_NUMBER
          - git push origin release-$BITBUCKET_BUILD_NUMBER
    - step:
        name: Build Docker Container and Deploy to Docker Hub
        script:
          - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
          - docker build -t gultech/boilerplate . --pull
          - docker push gultech/boilerplate
        services:
          - docker