# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step: Build Node application
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
    - step: Tag version
        caches:
            -node
        script:
            - echo tag version in git with number
    - step: Create Docker container
        caches:
            - node
        script:
            - docker version
        services:
            - docker
    - step: Deploy to Docker Hub
        caches:
            - node
        script:
            - echo deploy to Docker Hub
